### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by ghost** [dldx/hpstr-hugo-theme#1]
Great job @dldx! 😸  I used this theme for over a year before switching to Minimal mistakes and loved it. I'm sure @mmistakes will appreciate your work. Next up, Minimal Mistakes theme??

**Comment by dldx** [comment]
Hey, thanks for the comment @jhabdas! This was the first theme I ported and I'm also pretty new to Hugo/Go so it took me a while but I'd be happy to take a look at Minimal next... after I finish a site I'm working on and finish making a dark theme for hpstr! Sorry :P
