### ISSUE TITLE
Cannot display background image correctly

### ISSUE THREAD

**Issue by Endrhythm** [dldx/hpstr-hugo-theme#13]
Hi，dldx:heart:

When I post my article, there is somting wrong with my background image. the url of img is Okay. as can be seen below:
https://www.guankui.name/posts/2020/20200214/

and the whole repository is:
https://github.com/Boylad/boylad.github.io/tree/master/posts/2020/20200214

![image](https://user-images.githubusercontent.com/34851469/100193141-2f177680-2f2e-11eb-8ca6-29a119d4a5ea.png)

**Comment by Endrhythm** [comment]
> Hi，dldx❤️
> 
> When I post my article, there is somting wrong with my background image. the url of img is Okay. as can be seen below:
> https://www.guankui.name/posts/2020/20200214/
> 
> and the whole repository is:
> https://github.com/Boylad/boylad.github.io/tree/master/posts/2020/20200214
> 
> ![image](https://user-images.githubusercontent.com/34851469/100193141-2f177680-2f2e-11eb-8ca6-29a119d4a5ea.png)

I have fixed this problem.

**Comment by dldx** [comment]
Great! When I go to your site, the CSS doesn't load. Perhaps an issue with your URL? 

It says 
```html
<link rel="stylesheet" href="/www.guankui.name/css/main.min.css"/>
```

in the source. you need https:// or just /css
