### ISSUE TITLE
How do I modify the navigation menu?

### ISSUE THREAD

**Issue by vazh** [dldx/hpstr-hugo-theme#2]
hey dldx, thanks for the port. great job!.
anyway i dont know if i should be asking this in here or at the original jekyll repo.

so here's some questions::
- i moved the about menu into the main menu, removed the learn more, and put the link on the avatar & bio item. but it shrunk, because of anchor. can you tell me how to expand it to normal size?
- can i make the post menu extends without clicking it? hovering it without clicking it on desktop is pretty much easier for me i think.
- and last one, the email, twitter, fb, etc. button. how to make it only the icon, so it can fit 3 icon in a row.

can you help me with this? im not very good at css. if you can't, maybe you can give me some direction to it.

thx, regards.

**Comment by dldx** [comment]
Hey @vazh!

I implemented what you asked for in the "issue-#2" branch: https://github.com/dldx/hpstr-hugo-theme/tree/issue-%232

Hope it works for you! The only issue is that if you make the menu hover only, it won't work on mobile devices so I kept the click mode.

Let me know if you need anything else.

Cheers,
Durand

**Comment by vazh** [comment]
@dldx 
holy shit, that was super awesome. im checking it right now. its super flawless :+1: 
the menu hover is fine. the menu is what matter the most.
anyway, thanks a lot.

srsly though, that was fuckin awesome.
best regards, vazh.

**Comment by vazh** [comment]
@dldx sorry to make another question.
how to make the icon bigger, not really visible right now. :)
sorry >_<

**Comment by dldx** [comment]
Like so: https://github.com/dldx/hpstr-hugo-theme/commit/4e3f2f78313ae372252e74c9dcc4b78c6222997d

If you want to experiment with it, get sass, run it in the static/css directory using `sass --watch main.scss:main.css` and then change static/css/sass/_dl-menu.scss:125.

Hope that helps!

**Comment by vazh** [comment]
@dldx okay, thank you very much. much appreciated. 👍
