### ISSUE TITLE
Where is reading time calculated?

### ISSUE THREAD

**Issue by rwinikates** [dldx/hpstr-hugo-theme#5]
I see how it is done on the jekyll variant, but I have yet to find where it is calculated in this hugo version, can you point me to the right place?

**Comment by dldx** [comment]
Hey,

I didn't implement reading time in this theme because Hugo already has a
function to calculate it. See [.ReadingTime](
https://gohugo.io/templates/variables/)

Cheers,
Durand

**Comment by rwinikates** [comment]
🍰  amazing. Sorry for the noob question.

**Comment by dldx** [comment]
Glad I could help!
