### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by Delvis** [dldx/hpstr-hugo-theme#7]
The drop down menu seems a bit different (opening) when compared to Jekyll version, which is really smooth.
Hugo's version of hpstr seems to load in the middle of the screen, and only after a while goes into it's correct position. Or is it just me?

**Comment by miterion** [comment]
Somebody fixed it [upstream](https://github.com/mmistakes/hpstr-jekyll-theme/issues/170#issuecomment-316535862). I made a pull request #8 for the maintainer to merge.

**Comment by dldx** [comment]
@Delvis I'm so sorry but I never saw this issue as I've been very busy recently... I hope it works now with the new fix by @Miterion  (Thanks!)
