### ISSUE TITLE
Recent change seems to break code style

### ISSUE THREAD

**Issue by fernando-mc** [dldx/hpstr-hugo-theme#9]
It looks like a recent change to the main.css file removed a line that causes padding to work for code blocks. 

https://github.com/dldx/hpstr-hugo-theme/commit/0b63b36733ea416e2efe1f0a7884c67225fdca7b#diff-710f826a5b882ce3a513456aab8f915bL2905

![padding](https://user-images.githubusercontent.com/6182464/31001808-54c89150-a49b-11e7-91c0-c3036a0a975e.PNG)

**Comment by dldx** [comment]
Thanks for letting me know! Just pushed a fix: 379f600612589d22d37790002254aa9e16f57719.

**Comment by fernando-mc** [comment]
Awesome! You rock! I'll test it out and close this after I verify. Thanks for making this theme! fernandomc.com never looked better!

**Comment by fernando-mc** [comment]
@dldx Yep! Those changes seem to fix the formatting issue. No idea if they break the fix to the Nav (I wasn't sure what that fix did)

**Comment by dldx** [comment]
Sweet, thank you! Having looked at your blog, I noticed that the cover images on posts are not centred. I never noticed that before so I guess I need to investigate why that has happened....and fix that isSet warning too... 

 BTW, I didn't make the theme, just ported it to Hugo. Michael Rose (@mmistakes) did so all credit to him! :)

**Comment by fernando-mc** [comment]
Well, thanks to @mmistakes then too! And yeah, I noticed that recently too, let me know if I can help with that or the isSet warning! Both of those are issues for me haha.
